NDefines.NBuildings.MAX_SHARED_SLOTS = 50
NDefines.NCountry.MIN_STABILITY = -1.0
NDefines.NCountry.MIN_WAR_SUPPORT = -1.0
NDefines.NTrade.ANTI_MONOPOLY_TRADE_FACTOR_THRESHOLD = 0.65
NDefines.NTrade.ANTI_MONOPOLY_TRADE_FACTOR = -0.35
NDefines.NDiplomacy.TENSION_PEACE_FACTOR = -0.25
NDefines.NGame.START_DATE = "1965.1.1.12"
NDefines.NGame.END_DATE = "1990.1.1.12"